spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_db_dev?useSSL=false&serverTimezone=UTC
    username: dev_user
    password: dev_password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG
    com.courseplatform.courseservice: DEBUG