spring:
  application:
    name: course-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: amaan9876
    driver-class-name: com.mysql.cj.jdbc.Driver
    

  security:
   user:
    name: admin
    password: secret
  
  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
    timeout: 86400s  # 1 hour
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 24h
      cookie:
        name: SESSION
        http-only: true
        secure: false  # Set to true in production with HTTPS
        same-site: lax


logging:
  level:
    root: INFO
    com.courseplatform.courseservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# SMS Configuration (Twilio example)
# sms:
#   provider: 2factor
#   2factor:
#     account-sid: your_account_sid
#     auth-token: your_auth_token
#     phone-number: your_twilio_phone_number
